version: '3.3'

services:
  phoenix:
    container_name: "${PROJECT_NAME}_elixir"
    build: .
    depends_on:
      - postgres
      # - mariadb
    command: "bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; mix phx.digest && mix phx.server'"
    environment:
      MIX_ENV: $PROJECT_ENVIRONMENT
      DATABASE_URL: $PROJECT_DATABASE_URL
      SECRET_KEY_BASE: $PROJECT_SECRET
      PORT: $PROJECT_PORT
    ports:
      - $PROJECT_PORT:$PROJECT_PORT
    volumes:
      - .:/app

  postgres:
    container_name: "${PROJECT_NAME}_postgres"
    image: postgres:$POSTGRES_TAG
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  # mariadb:
  #   container_name: "${PROJECT_NAME}_mariadb"
  #   image: mariadb:$MARIADB_TAG
  #   environment:
  #     MYSQL_DATABASE: $MARIADB_DB
  #     MYSQL_USER: $MARIADB_USER
  #     MYSQL_ROOT_PASSWORD: $MARIADB_PASSWORD
  #     MYSQL_PASSWORD: $MARIADB_PASSWORD
