version: '3.3'

services:
  postgres:
    container_name: "${PROJECT_NAME}_postgres"
    image: postgres:$POSTGRES_TAG
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  phoenix:
    container_name: "${PROJECT_NAME}_elixir"
    build: .
    depends_on:
      - postgres
    command: "bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; mix phx.digest && mix phx.server'"
    environment:
      MIX_ENV: $PROJECT_ENVIRONMENT
      DATABASE_URL: $PROJECT_DATABASE_URL
      SECRET_KEY_BASE: $PROJECT_SECRET
      PORT: $PROJECT_PORT
    ports:
      - $PROJECT_PORT:$PROJECT_PORT
    volumes:
      - .:/app
